version: '3.8'
services:

  db-service:
    container_name: db-service
    image: db-service:1.0
    build:
      context: src/main/resources/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: davito_db
    ports:
      - "15432:5432"
    restart: unless-stopped